//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppFuel
    {
        public int FlightId { get; set; }
        public Nullable<decimal> UpLift { get; set; }
        public Nullable<decimal> FuelTotal { get; set; }
        public Nullable<decimal> ExtraFuel { get; set; }
        public Nullable<decimal> Remaining { get; set; }
        public Nullable<decimal> UsedFuel { get; set; }
        public decimal UsedFuelAvg { get; set; }
        public decimal UsedFuelAvgReg { get; set; }
        public Nullable<int> Taxi { get; set; }
        public Nullable<int> FPTripFuel { get; set; }
        public Nullable<int> FPFuel { get; set; }
        public Nullable<int> FuelUsedEng1 { get; set; }
        public Nullable<int> FuelUsedEng2 { get; set; }
        public Nullable<int> FuelUsedEng { get; set; }
        public Nullable<decimal> DifTripFuel { get; set; }
        public Nullable<decimal> DifTripFuelPercent { get; set; }
        public Nullable<decimal> DifTotalFuel { get; set; }
        public Nullable<decimal> DifTotalFuelPercent { get; set; }
        public Nullable<decimal> FPVar { get; set; }
        public Nullable<int> TotalPax { get; set; }
        public int FuelUnitID { get; set; }
        public string FuelUnit { get; set; }
        public int BaggageWeight { get; set; }
        public int CargoWeight { get; set; }
        public Nullable<int> Freight { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> BlockOn { get; set; }
        public Nullable<System.DateTime> BlockOff { get; set; }
        public Nullable<System.DateTime> TakeOff { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public string Register { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string AircraftType { get; set; }
        public Nullable<int> FromAirportId { get; set; }
        public Nullable<int> ToAirportId { get; set; }
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<int> DelayBlockOff { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<decimal> FuelDensity { get; set; }
        public Nullable<decimal> CARGO { get; set; }
        public string PF { get; set; }
        public string PIC { get; set; }
        public Nullable<int> PICId { get; set; }
        public string SIC { get; set; }
        public Nullable<int> SICId { get; set; }
        public string ALT1 { get; set; }
        public string ALT2 { get; set; }
        public string ALT3 { get; set; }
        public string IPName { get; set; }
        public Nullable<int> IPId { get; set; }
        public string IPScheduleName { get; set; }
        public string P1Name { get; set; }
        public Nullable<int> P1Id { get; set; }
        public string P1ScheduleName { get; set; }
        public string P2Name { get; set; }
        public Nullable<int> P2Id { get; set; }
        public string P2ScheduleName { get; set; }
        public int PaxAdult { get; set; }
        public int PaxChild { get; set; }
        public int PaxInfant { get; set; }
        public Nullable<int> RevPax { get; set; }
        public string PDate { get; set; }
        public Nullable<int> PYear { get; set; }
        public string PMonthName { get; set; }
        public Nullable<int> PMonth { get; set; }
        public string PDayName { get; set; }
        public Nullable<int> PDay { get; set; }
        public int Season { get; set; }
        public string SeasonTitle { get; set; }
        public string PYearMonthName { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public int std_hour_0004 { get; set; }
        public int std_hour_0408 { get; set; }
        public int std_hour_0812 { get; set; }
        public int std_hour_1216 { get; set; }
        public int std_hour_1620 { get; set; }
        public int std_hour_2024 { get; set; }
    }
}
