//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_hazard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms2_hazard()
        {
            this.cms2_hazard_cause = new HashSet<cms2_hazard_cause>();
            this.cms2_hazard_consequence = new HashSet<cms2_hazard_consequence>();
            this.cms2_hazard_org_unit = new HashSet<cms2_hazard_org_unit>();
            this.cms2_risk_assessment_log = new HashSet<cms2_risk_assessment_log>();
            this.cms2_audit_hazard = new HashSet<cms2_audit_hazard>();
            this.cms2_occurrence_hazard = new HashSet<cms2_occurrence_hazard>();
        }
    
        public int id { get; set; }
        public int hazard_type_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime identified_date { get; set; }
        public Nullable<System.DateTime> last_review_date { get; set; }
        public Nullable<System.DateTime> next_review_due_date { get; set; }
        public bool is_active { get; set; }
        public string risk_owner { get; set; }
        public string responsible_department { get; set; }
        public string initial_severity_code { get; set; }
        public string initial_likelihood_code { get; set; }
        public string initial_risk_level_code { get; set; }
        public string residual_severity_code { get; set; }
        public string residual_likelihood_code { get; set; }
        public string residual_risk_level_code { get; set; }
        public string risk_acceptance_status { get; set; }
        public Nullable<System.DateTime> risk_acceptance_date { get; set; }
        public string risk_accepted_by { get; set; }
        public string risk_matrix_version { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public byte[] row_version { get; set; }
        public int hazard_status_id { get; set; }
        public Nullable<int> initial_severity_id { get; set; }
        public Nullable<int> initial_likelihood_id { get; set; }
        public Nullable<int> initial_risk_level_id { get; set; }
        public Nullable<int> residual_severity_id { get; set; }
        public Nullable<int> residual_likelihood_id { get; set; }
        public Nullable<int> residual_risk_level_id { get; set; }
        public Nullable<int> risk_matrix_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_hazard_cause> cms2_hazard_cause { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_hazard_consequence> cms2_hazard_consequence { get; set; }
        public virtual cms2_risk_likelihood cms2_risk_likelihood { get; set; }
        public virtual cms2_risk_level cms2_risk_level { get; set; }
        public virtual cms2_risk_severity cms2_risk_severity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_hazard_org_unit> cms2_hazard_org_unit { get; set; }
        public virtual cms2_risk_likelihood cms2_risk_likelihood1 { get; set; }
        public virtual cms2_risk_level cms2_risk_level1 { get; set; }
        public virtual cms2_risk_severity cms2_risk_severity1 { get; set; }
        public virtual cms2_risk_matrix cms2_risk_matrix { get; set; }
        public virtual cms2_hazard_status cms2_hazard_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_risk_assessment_log> cms2_risk_assessment_log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_hazard> cms2_audit_hazard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_occurrence_hazard> cms2_occurrence_hazard { get; set; }
    }
}
