//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_audit_team
    {
        public int id { get; set; }
        public int audit_id { get; set; }
        public int auditor_id { get; set; }
        public int role_id { get; set; }
        public bool is_lead { get; set; }
    
        public virtual cms2_audit cms2_audit { get; set; }
        public virtual cms2_auditors cms2_auditors { get; set; }
        public virtual cms2_audit_team_role cms2_audit_team_role { get; set; }
    }
}
