//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_hazard_consequence
    {
        public int id { get; set; }
        public int hazard_id { get; set; }
        public Nullable<int> consequence_category_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string severity_code { get; set; }
        public bool is_active { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual cms2_hazard cms2_hazard { get; set; }
        public virtual cms2_hazard_consequence_category cms2_hazard_consequence_category { get; set; }
    }
}
