//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_risk_matrix_cell
    {
        public int id { get; set; }
        public int risk_matrix_id { get; set; }
        public int risk_severity_id { get; set; }
        public int risk_likelihood_id { get; set; }
        public int risk_level_id { get; set; }
        public string ui_color_code { get; set; }
        public string note { get; set; }
    
        public virtual cms2_risk_level cms2_risk_level { get; set; }
        public virtual cms2_risk_likelihood cms2_risk_likelihood { get; set; }
        public virtual cms2_risk_matrix cms2_risk_matrix { get; set; }
        public virtual cms2_risk_severity cms2_risk_severity { get; set; }
    }
}
