//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_audit_ref
    {
        public int id { get; set; }
        public int audit_id { get; set; }
        public int doc_id { get; set; }
        public Nullable<int> clause_id { get; set; }
        public Nullable<byte> weight { get; set; }
        public string note { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual cms2_audit cms2_audit { get; set; }
        public virtual cms2_ref_clause cms2_ref_clause { get; set; }
        public virtual cms2_ref_doc cms2_ref_doc { get; set; }
    }
}
