//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_ref_doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms2_ref_doc()
        {
            this.cms2_audit_finding_ref = new HashSet<cms2_audit_finding_ref>();
            this.cms2_audit_plan_ref = new HashSet<cms2_audit_plan_ref>();
            this.cms2_audit_ref = new HashSet<cms2_audit_ref>();
            this.cms2_ref_clause = new HashSet<cms2_ref_clause>();
        }
    
        public int id { get; set; }
        public string doc_type { get; set; }
        public string title { get; set; }
        public string issuer { get; set; }
        public string edition { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public string status { get; set; }
        public string url { get; set; }
        public string notes { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_finding_ref> cms2_audit_finding_ref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_plan_ref> cms2_audit_plan_ref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_ref> cms2_audit_ref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_ref_clause> cms2_ref_clause { get; set; }
    }
}
