//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_risk_assessment_log
    {
        public int id { get; set; }
        public int hazard_id { get; set; }
        public Nullable<int> risk_matrix_id { get; set; }
        public string assessment_type { get; set; }
        public System.DateTime assessment_date { get; set; }
        public string assessed_by { get; set; }
        public string assessed_role { get; set; }
        public Nullable<int> initial_severity_id { get; set; }
        public Nullable<int> initial_likelihood_id { get; set; }
        public Nullable<int> initial_risk_level_id { get; set; }
        public Nullable<int> residual_severity_id { get; set; }
        public Nullable<int> residual_likelihood_id { get; set; }
        public Nullable<int> residual_risk_level_id { get; set; }
        public string risk_acceptance_status { get; set; }
        public string risk_accepted_by { get; set; }
        public Nullable<System.DateTime> risk_acceptance_date { get; set; }
        public string comment { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
        public byte[] row_version { get; set; }
    
        public virtual cms2_hazard cms2_hazard { get; set; }
        public virtual cms2_risk_likelihood cms2_risk_likelihood { get; set; }
        public virtual cms2_risk_level cms2_risk_level { get; set; }
        public virtual cms2_risk_severity cms2_risk_severity { get; set; }
        public virtual cms2_risk_matrix cms2_risk_matrix { get; set; }
        public virtual cms2_risk_likelihood cms2_risk_likelihood1 { get; set; }
        public virtual cms2_risk_level cms2_risk_level1 { get; set; }
        public virtual cms2_risk_severity cms2_risk_severity1 { get; set; }
    }
}
