//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_ref_clause
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms2_ref_clause()
        {
            this.cms2_audit_finding_ref = new HashSet<cms2_audit_finding_ref>();
            this.cms2_audit_plan_ref = new HashSet<cms2_audit_plan_ref>();
            this.cms2_audit_ref = new HashSet<cms2_audit_ref>();
            this.cms2_ref_clause1 = new HashSet<cms2_ref_clause>();
        }
    
        public int id { get; set; }
        public int doc_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string clause_code { get; set; }
        public string title { get; set; }
        public string clause_text { get; set; }
        public bool is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_finding_ref> cms2_audit_finding_ref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_plan_ref> cms2_audit_plan_ref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_ref> cms2_audit_ref { get; set; }
        public virtual cms2_ref_doc cms2_ref_doc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_ref_clause> cms2_ref_clause1 { get; set; }
        public virtual cms2_ref_clause cms2_ref_clause2 { get; set; }
    }
}
