//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFBBirdStrikeCAO
    {
        public int Id { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string EngineModel { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> LocalTimeId { get; set; }
        public string AerodromeName { get; set; }
        public string RunwayUsed { get; set; }
        public string EnRouteLoc { get; set; }
        public Nullable<decimal> HeightAGl { get; set; }
        public Nullable<decimal> Speed_IAS_ { get; set; }
        public Nullable<int> PhaseOrFlightId { get; set; }
        public Nullable<int> A_CPartRadom { get; set; }
        public Nullable<int> A_CPartWindShield { get; set; }
        public Nullable<int> A_CPartNose { get; set; }
        public Nullable<int> A_CPartEngineNO1 { get; set; }
        public Nullable<int> A_CPartEngineNO2 { get; set; }
        public Nullable<int> A_CPartEngineNO3 { get; set; }
        public Nullable<int> A_CPartEngineNO4 { get; set; }
        public Nullable<int> A_CPartPropeller { get; set; }
        public Nullable<int> A_CPartWing_Rotor { get; set; }
        public Nullable<int> A_CPartFuselage { get; set; }
        public Nullable<int> A_CPartLandingGear { get; set; }
        public Nullable<int> A_CPartTail { get; set; }
        public Nullable<int> A_CPartLight { get; set; }
        public Nullable<int> A_CPartOther_Specify_ { get; set; }
        public Nullable<bool> IsEffect__None { get; set; }
        public Nullable<bool> IsEffectAbortedTakeOff { get; set; }
        public Nullable<bool> IsEffectLanding { get; set; }
        public Nullable<bool> IsEffectEngineShutDown { get; set; }
        public Nullable<bool> IsEffectOther { get; set; }
        public Nullable<int> SkyConditionId { get; set; }
        public Nullable<int> IsPrecipitationFog { get; set; }
        public Nullable<int> IsPrecipitationRain { get; set; }
        public Nullable<int> IsPrecipitationSnow { get; set; }
        public string BirdSpecies { get; set; }
        public Nullable<int> BirdNrSeenId { get; set; }
        public Nullable<int> BirdNrStruckId { get; set; }
        public Nullable<int> BirdSizeId { get; set; }
        public Nullable<bool> IspilotWarned { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ReportedById { get; set; }
    }
}
