//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFBConfidentialReport
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> LocalTime { get; set; }
        public Nullable<System.DateTime> UTCTime { get; set; }
        public Nullable<bool> IsDay { get; set; }
        public string EventSummary { get; set; }
        public string ActionTaken { get; set; }
        public string Resolve { get; set; }
        public string SafetyRECO { get; set; }
        public string Other { get; set; }
        public Nullable<bool> ASRRaised { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string User { get; set; }
        public string DateUpdate { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> EmpNo { get; set; }
    }
}
