//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFBDSPRelease
    {
        public Nullable<int> FlightId { get; set; }
        public Nullable<bool> ActualWXDSP { get; set; }
        public Nullable<bool> ActualWXCPT { get; set; }
        public string ActualWXDSPRemark { get; set; }
        public string ActualWXCPTRemark { get; set; }
        public Nullable<bool> WXForcastDSP { get; set; }
        public Nullable<bool> WXForcastCPT { get; set; }
        public string WXForcastDSPRemark { get; set; }
        public string WXForcastCPTRemark { get; set; }
        public Nullable<bool> SigxWXDSP { get; set; }
        public Nullable<bool> SigxWXCPT { get; set; }
        public string SigxWXDSPRemark { get; set; }
        public string SigxWXCPTRemark { get; set; }
        public Nullable<bool> WindChartDSP { get; set; }
        public Nullable<bool> WindChartCPT { get; set; }
        public string WindChartDSPRemark { get; set; }
        public string WindChartCPTRemark { get; set; }
        public Nullable<bool> NotamDSP { get; set; }
        public Nullable<bool> NotamCPT { get; set; }
        public string NotamDSPRemark { get; set; }
        public string NotamCPTRemark { get; set; }
        public Nullable<bool> ComputedFligthPlanDSP { get; set; }
        public Nullable<bool> ComputedFligthPlanCPT { get; set; }
        public string ComputedFligthPlanDSPRemark { get; set; }
        public string ComputedFligthPlanCPTRemark { get; set; }
        public Nullable<bool> ATCFlightPlanDSP { get; set; }
        public Nullable<bool> ATCFlightPlanCPT { get; set; }
        public string ATCFlightPlanDSPRemark { get; set; }
        public string ATCFlightPlanCPTRemark { get; set; }
        public Nullable<bool> PermissionsDSP { get; set; }
        public Nullable<bool> PermissionsCPT { get; set; }
        public string PermissionsDSPRemark { get; set; }
        public string PermissionsCPTRemark { get; set; }
        public Nullable<bool> JeppesenAirwayManualDSP { get; set; }
        public Nullable<bool> JeppesenAirwayManualCPT { get; set; }
        public string JeppesenAirwayManualDSPRemark { get; set; }
        public string JeppesenAirwayManualCPTRemark { get; set; }
        public Nullable<bool> MinFuelRequiredDSP { get; set; }
        public Nullable<bool> MinFuelRequiredCPT { get; set; }
        public Nullable<decimal> MinFuelRequiredCFP { get; set; }
        public Nullable<decimal> MinFuelRequiredPilotReq { get; set; }
        public Nullable<bool> GeneralDeclarationDSP { get; set; }
        public Nullable<bool> GeneralDeclarationCPT { get; set; }
        public string GeneralDeclarationDSPRemark { get; set; }
        public string GeneralDeclarationCPTRemark { get; set; }
        public Nullable<bool> FlightReportDSP { get; set; }
        public Nullable<bool> FlightReportCPT { get; set; }
        public string FlightReportDSPRemark { get; set; }
        public string FlightReportCPTRemark { get; set; }
        public Nullable<bool> TOLndCardsDSP { get; set; }
        public Nullable<bool> TOLndCardsCPT { get; set; }
        public string TOLndCardsDSPRemark { get; set; }
        public string TOLndCardsCPTRemark { get; set; }
        public Nullable<bool> LoadSheetDSP { get; set; }
        public Nullable<bool> LoadSheetCPT { get; set; }
        public string LoadSheetDSPRemark { get; set; }
        public string LoadSheetCPTRemark { get; set; }
        public Nullable<bool> FlightSafetyReportDSP { get; set; }
        public Nullable<bool> FlightSafetyReportCPT { get; set; }
        public string FlightSafetyReportDSPRemark { get; set; }
        public string FlightSafetyReportCPTRemark { get; set; }
        public Nullable<bool> AVSECIncidentReportDSP { get; set; }
        public Nullable<bool> AVSECIncidentReportCPT { get; set; }
        public string AVSECIncidentReportDSPRemark { get; set; }
        public string AVSECIncidentReportCPTRemark { get; set; }
        public Nullable<bool> OperationEngineeringDSP { get; set; }
        public Nullable<bool> OperationEngineeringCPT { get; set; }
        public string OperationEngineeringDSPRemark { get; set; }
        public string OperationEngineeringCPTRemark { get; set; }
        public Nullable<bool> VoyageReportDSP { get; set; }
        public Nullable<bool> VoyageReportCPT { get; set; }
        public string VoyageReportDSPRemark { get; set; }
        public string VoyageReportCPTRemark { get; set; }
        public Nullable<bool> PIFDSP { get; set; }
        public Nullable<bool> PIFCPT { get; set; }
        public string PIFDSPRemark { get; set; }
        public string PIFCPTRemark { get; set; }
        public Nullable<bool> GoodDeclarationDSP { get; set; }
        public Nullable<bool> GoodDeclarationCPT { get; set; }
        public string GoodDeclarationDSPRemark { get; set; }
        public string GoodDeclarationCPTRemark { get; set; }
        public Nullable<bool> IPADDSP { get; set; }
        public Nullable<bool> IPADCPT { get; set; }
        public string IPADDSPRemark { get; set; }
        public string IPADCPTRemark { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<int> DispatcherId { get; set; }
        public int Id { get; set; }
        public string DateUpdate { get; set; }
        public string User { get; set; }
        public string JLSignedBy { get; set; }
        public Nullable<System.DateTime> JLDatePICApproved { get; set; }
        public Nullable<int> PICId { get; set; }
        public string PIC { get; set; }
        public Nullable<bool> OperationalFlightPlanFOO { get; set; }
        public Nullable<bool> OperationalFlightPlanCMDR { get; set; }
        public string OperationalFlightPlanFOORemark { get; set; }
        public string OperationalFlightPlanCMDRRemark { get; set; }
        public Nullable<bool> ATSFlightPlanFOO { get; set; }
        public Nullable<bool> ATSFlightPlanCMDR { get; set; }
        public string ATSFlightPlanFOORemark { get; set; }
        public string ATSFlightPlanCMDRRemark { get; set; }
        public Nullable<bool> VldEFBFOO { get; set; }
        public Nullable<bool> VldEFBCMDR { get; set; }
        public string VldEFBFOORemark { get; set; }
        public string VldEFBCMDRRemark { get; set; }
        public Nullable<bool> VldFlightCrewFOO { get; set; }
        public Nullable<bool> VldFlightCrewCMDR { get; set; }
        public string VldFlightCrewFOORemark { get; set; }
        public string VldFlightCrewCMDRRemark { get; set; }
        public Nullable<bool> VldMedicalFOO { get; set; }
        public Nullable<bool> VldMedicalCMDR { get; set; }
        public string VldMedicalFOORemark { get; set; }
        public string VldMedicalCMDRRemark { get; set; }
        public Nullable<bool> VldPassportFOO { get; set; }
        public Nullable<bool> VldPassportCMDR { get; set; }
        public string VldPassportFOORemark { get; set; }
        public string VldPassportCMDRRemark { get; set; }
        public Nullable<bool> VldCMCFOO { get; set; }
        public Nullable<bool> VldCMCCMDR { get; set; }
        public string VldCMCFOORemark { get; set; }
        public string VldCMCCMDRRemark { get; set; }
        public Nullable<bool> VldRampPassFOO { get; set; }
        public Nullable<bool> VldRampPassCMDR { get; set; }
        public string VldRampPassFOORemark { get; set; }
        public string VldRampPassCMDRRemark { get; set; }
        public string Note { get; set; }
        public string SgnDSPLicNo { get; set; }
        public string SgnCPTLicNo { get; set; }
        public Nullable<System.DateTime> JLDSPSignDate { get; set; }
        public string SGNDSPName { get; set; }
        public string ipad_no_1 { get; set; }
        public string ipad_no_2 { get; set; }
        public string ipad_no_3 { get; set; }
        public string pb_1 { get; set; }
        public string pb_2 { get; set; }
    }
}
