//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFBValue
    {
        public int Id { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public Nullable<System.DateTime> FieldValueDate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string UserName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string TableKey { get; set; }
        public Nullable<int> TableKeyValueInt { get; set; }
        public string TableKey2 { get; set; }
        public string TableKey2Value { get; set; }
    }
}
