//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_hazard_relevant
    {
        public int id { get; set; }
        public Nullable<int> hazard_id { get; set; }
        public Nullable<int> relevant_id { get; set; }
        public string remark { get; set; }
    
        public virtual qa_hazard qa_hazard { get; set; }
        public virtual qa_hazard qa_hazard1 { get; set; }
    }
}
