//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_hazard_source
    {
        public int id { get; set; }
        public Nullable<int> source_type { get; set; }
        public string title { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<int> audit_id { get; set; }
        public Nullable<int> reporter_id { get; set; }
        public string reporter { get; set; }
        public Nullable<System.DateTime> date_reported { get; set; }
        public string remark { get; set; }
        public Nullable<int> hazard_id { get; set; }
        public Nullable<bool> is_confidential { get; set; }
        public Nullable<bool> is_anonymous { get; set; }
    
        public virtual qa_hazard qa_hazard { get; set; }
    }
}
