//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_notification_history
    {
        public int id { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<int> entity_type { get; set; }
        public string rec_name { get; set; }
        public string rec_mobile { get; set; }
        public Nullable<int> rec_id { get; set; }
        public Nullable<int> message_type { get; set; }
        public Nullable<System.DateTime> date_send { get; set; }
        public string ref_id { get; set; }
        public string status { get; set; }
        public string message_text { get; set; }
        public Nullable<int> counter { get; set; }
    }
}
