//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cms2_audit_program
    {
        public int id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string program_type { get; set; }
        public System.DateTime period_from { get; set; }
        public System.DateTime period_to { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string notes { get; set; }
    }
}
