//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQAFollowingUp
    {
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public string TypeTitle { get; set; }
        public Nullable<int> EntityId { get; set; }
        public int ReferrerId { get; set; }
        public string ReferrerName { get; set; }
        public Nullable<int> ReferredId { get; set; }
        public string ReferredName { get; set; }
        public Nullable<int> ReviewResult { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
        public string ReviewResultTitle { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public string Priority { get; set; }
        public int ReceiverDateVisit { get; set; }
        public Nullable<int> FlightId { get; set; }
    }
}
