//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEFBVoyageReport
    {
        public int Id { get; set; }
        public string Route { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> RestReduction { get; set; }
        public Nullable<int> DutyExtention { get; set; }
        public string Report { get; set; }
        public Nullable<System.DateTime> DatePICSignature { get; set; }
        public Nullable<int> ActionedById { get; set; }
        public Nullable<System.DateTime> DateActioned { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public string Irrs { get; set; }
        public string Reasons { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BlockOn { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> TakeOff { get; set; }
        public Nullable<System.DateTime> BlockOff { get; set; }
        public Nullable<System.DateTime> BlockOnLocal { get; set; }
        public Nullable<System.DateTime> LandingLocal { get; set; }
        public Nullable<System.DateTime> TakeOffLocal { get; set; }
        public Nullable<System.DateTime> BlockOffLocal { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public string AircraftType { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string Register { get; set; }
        public int MSN { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<System.DateTime> STDDayLocal { get; set; }
        public Nullable<System.DateTime> STADayLocal { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> DepartureLocal { get; set; }
        public Nullable<System.DateTime> ArrivalLocal { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> ScheduledFlightTime { get; set; }
        public Nullable<int> PFLR { get; set; }
        public Nullable<int> FPFlightTime { get; set; }
        public Nullable<int> PaxChild { get; set; }
        public Nullable<int> PaxInfant { get; set; }
        public Nullable<int> PaxAdult { get; set; }
        public Nullable<int> PaxTotal { get; set; }
        public Nullable<int> PaxRevenued { get; set; }
        public Nullable<int> FuelUnitID { get; set; }
        public Nullable<decimal> FuelRemaining { get; set; }
        public Nullable<decimal> FuelUplift { get; set; }
        public Nullable<decimal> FuelUsed { get; set; }
        public Nullable<decimal> FuelTotal { get; set; }
        public Nullable<int> TotalSeat { get; set; }
        public int BaggageWeight { get; set; }
        public int CargoWeight { get; set; }
        public Nullable<int> Freight { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<int> CargoCount { get; set; }
        public Nullable<int> BaggageCount { get; set; }
        public Nullable<decimal> FPFuel { get; set; }
        public Nullable<int> CPCrewId { get; set; }
        public string CPRegister { get; set; }
        public Nullable<int> CPPositionId { get; set; }
        public Nullable<int> CPFlightTypeId { get; set; }
        public Nullable<int> CPFDPItemId { get; set; }
        public Nullable<bool> CPDH { get; set; }
        public Nullable<int> CPFDPId { get; set; }
        public string CPInstructor { get; set; }
        public string CPP1 { get; set; }
        public string CPP2 { get; set; }
        public string CPSCCM { get; set; }
        public string CPISCCM { get; set; }
        public int NightTime { get; set; }
        public Nullable<int> DayTime { get; set; }
        public Nullable<int> JLUserId { get; set; }
        public Nullable<int> JLApproverId { get; set; }
        public Nullable<System.DateTime> JLDateApproved { get; set; }
        public Nullable<System.DateTime> JLDate { get; set; }
        public string JLNo { get; set; }
        public string SerialNo { get; set; }
        public string LTR { get; set; }
        public Nullable<decimal> RVSM_GND_CPT { get; set; }
        public Nullable<decimal> RVSM_GND_STBY { get; set; }
        public Nullable<decimal> RVSM_GND_FO { get; set; }
        public Nullable<decimal> RVSM_FLT_CPT { get; set; }
        public Nullable<decimal> RVSM_FLT_STBY { get; set; }
        public Nullable<decimal> RVSM_FLT_FO { get; set; }
        public Nullable<decimal> CARGO { get; set; }
        public Nullable<decimal> FuelDensity { get; set; }
        public string CommanderNote { get; set; }
        public Nullable<bool> AttASR { get; set; }
        public Nullable<bool> AttVoyageReport { get; set; }
        public Nullable<bool> AttRepositioning1 { get; set; }
        public Nullable<bool> AttRepositioning2 { get; set; }
        public string JLUser { get; set; }
        public string JLApprover { get; set; }
        public int IsJL { get; set; }
        public Nullable<int> Version { get; set; }
        public int IsJLApproved { get; set; }
        public string PF { get; set; }
        public string IPName { get; set; }
        public Nullable<int> IPId { get; set; }
        public string IPScheduleName { get; set; }
        public string P1Name { get; set; }
        public Nullable<int> P1Id { get; set; }
        public string P1ScheduleName { get; set; }
        public string P2Name { get; set; }
        public Nullable<int> P2Id { get; set; }
        public string P2ScheduleName { get; set; }
        public string PIC { get; set; }
        public Nullable<int> PICId { get; set; }
        public string SIC { get; set; }
        public Nullable<int> SICId { get; set; }
        public Nullable<System.DateTime> JLDatePICApproved { get; set; }
        public Nullable<int> DepDelay { get; set; }
        public string DateUpdate { get; set; }
        public string User { get; set; }
        public Nullable<int> ReporterId { get; set; }
        public Nullable<int> FormNo { get; set; }
        public Nullable<System.DateTime> DateOccurrence { get; set; }
        public string Result { get; set; }
        public Nullable<bool> AttForm_ASR { get; set; }
        public Nullable<bool> AttForm_CSR { get; set; }
        public Nullable<bool> AttForm_CR { get; set; }
        public Nullable<bool> AttForm_Other { get; set; }
        public string ActionTaken { get; set; }
        public Nullable<bool> IsForInformation { get; set; }
        public Nullable<bool> IsActionRequired { get; set; }
        public string OtherForm { get; set; }
        public Nullable<bool> AttForm_ACCIDET { get; set; }
    }
}
