//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cms2_audit_finding
    {
        public int id { get; set; }
        public int audit_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string level { get; set; }
        public string level_title { get; set; }
        public Nullable<int> standard_id { get; set; }
        public string standard_title { get; set; }
        public string standard_description { get; set; }
        public string none_compliance_description { get; set; }
        public System.DateTime closure_deadline { get; set; }
        public Nullable<System.DateTime> sent_report_date { get; set; }
        public Nullable<System.DateTime> closure_auditor_date { get; set; }
        public Nullable<System.DateTime> verified_qa_date { get; set; }
        public Nullable<int> auditor_id { get; set; }
        public string auditor_name { get; set; }
        public Nullable<int> verified_qa_by { get; set; }
        public string verified_qa_name { get; set; }
    }
}
