//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEFBVoyageReportsAll
    {
        public int Id { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string AircraftType { get; set; }
        public string Register { get; set; }
        public string OriginIATA { get; set; }
        public string DestinationIATA { get; set; }
        public string Route { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> RestReduction { get; set; }
        public Nullable<int> DutyExtention { get; set; }
        public string Report { get; set; }
        public Nullable<System.DateTime> DatePICSignature { get; set; }
        public Nullable<int> ActionedById { get; set; }
        public Nullable<System.DateTime> DateActioned { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public string Name { get; set; }
        public string PID { get; set; }
        public string NID { get; set; }
        public string Mobile { get; set; }
    }
}
