//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewQABYEmployee
    {
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> FollowingId { get; set; }
        public string Category { get; set; }
        public Nullable<int> ReviewResult { get; set; }
        public string ReviewResultTitle { get; set; }
    }
}
