//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cms2_audit_plan_ref
    {
        public int id { get; set; }
        public int audit_plan_id { get; set; }
        public int doc_id { get; set; }
        public string doc_type { get; set; }
        public string doc_title { get; set; }
        public Nullable<int> clause_id { get; set; }
        public string clause_code { get; set; }
        public string clause_title { get; set; }
        public Nullable<byte> weight { get; set; }
        public string note { get; set; }
        public System.DateTime created_at { get; set; }
    }
}
