//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_occurrence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms2_occurrence()
        {
            this.cms2_occurrence_source = new HashSet<cms2_occurrence_source>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime event_utc { get; set; }
        public string flight_number { get; set; }
        public string aircraft_registration { get; set; }
        public string dep_aerodrome_icao { get; set; }
        public string arr_aerodrome_icao { get; set; }
        public string phase_of_flight { get; set; }
        public string severity_code { get; set; }
        public string classification_code { get; set; }
        public bool is_active { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public byte[] row_version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_occurrence_source> cms2_occurrence_source { get; set; }
    }
}
