//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_occurrence_source
    {
        public int id { get; set; }
        public int occurrence_id { get; set; }
        public string source_type { get; set; }
        public string source_table { get; set; }
        public string source_pk { get; set; }
        public string source_ref { get; set; }
        public string description { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual cms2_occurrence cms2_occurrence { get; set; }
    }
}
