//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms2_audit()
        {
            this.cms2_audit_team = new HashSet<cms2_audit_team>();
            this.cms2_audit_hazard = new HashSet<cms2_audit_hazard>();
            this.cms2_audit_finding = new HashSet<cms2_audit_finding>();
            this.cms2_audit_corrective_action = new HashSet<cms2_audit_corrective_action>();
            this.cms2_audit_ref = new HashSet<cms2_audit_ref>();
        }
    
        public int id { get; set; }
        public Nullable<int> audit_plan_id { get; set; }
        public string title { get; set; }
        public string code { get; set; }
        public Nullable<int> auditee_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string audit_location { get; set; }
        public string scope { get; set; }
        public string area { get; set; }
        public Nullable<System.DateTime> audit_date { get; set; }
        public string standards_refrences { get; set; }
        public Nullable<int> created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> auditor_id { get; set; }
        public string remark { get; set; }
        public string scheduling_type { get; set; }
        public string audit_method { get; set; }
        public string execution_mode { get; set; }
        public string status { get; set; }
        public Nullable<int> audit_program_id { get; set; }
        public Nullable<System.DateTime> scheduled_start { get; set; }
        public Nullable<System.DateTime> scheduled_end { get; set; }
        public Nullable<System.DateTime> actual_start { get; set; }
        public Nullable<System.DateTime> actual_end { get; set; }
        public Nullable<System.DateTime> opening_meeting_start { get; set; }
        public Nullable<System.DateTime> opening_meeting_end { get; set; }
        public string opening_meeting_venue { get; set; }
        public Nullable<System.DateTime> closing_meeting_start { get; set; }
        public Nullable<System.DateTime> closing_meeting_end { get; set; }
        public string closing_meeting_venue { get; set; }
        public Nullable<int> department_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_team> cms2_audit_team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_hazard> cms2_audit_hazard { get; set; }
        public virtual cms2_auditors cms2_auditors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_finding> cms2_audit_finding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_corrective_action> cms2_audit_corrective_action { get; set; }
        public virtual cms2_audit_program cms2_audit_program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms2_audit_ref> cms2_audit_ref { get; set; }
    }
}
