//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms2_hazard_org_unit
    {
        public int id { get; set; }
        public int hazard_id { get; set; }
        public int org_unit_id { get; set; }
        public string role { get; set; }
        public string comment { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual cms2_hazard cms2_hazard { get; set; }
        public virtual cms2_org_unit cms2_org_unit { get; set; }
    }
}
