//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_nav_log
    {
        public int id { get; set; }
        public Nullable<int> flight_id { get; set; }
        public string deficiency_in { get; set; }
        public string rca { get; set; }
        public string cap { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.DateTime> date_sign { get; set; }
        public string pic { get; set; }
        public string lic_no { get; set; }
        public Nullable<System.DateTime> ops_date_sign { get; set; }
        public string ops_sign { get; set; }
        public string ops_lic_no { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public string remark { get; set; }
        public Nullable<int> pic_id { get; set; }
        public Nullable<int> ops_id { get; set; }
    }
}
