//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFBOccurrenceCAO
    {
        public int Id { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> ReporterId { get; set; }
        public Nullable<int> OccurrenceTypeId { get; set; }
        public Nullable<System.DateTime> OccurrenceDate { get; set; }
        public Nullable<bool> IsDay { get; set; }
        public string Location { get; set; }
        public string Altitude { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public Nullable<int> ACFlightPhaseId { get; set; }
        public string ACFlightPhaseRemark { get; set; }
        public string EquipmentType { get; set; }
        public string EquipmentAirportPlacard { get; set; }
        public string EquipmentCompany { get; set; }
        public string EquipmentDriverName { get; set; }
        public string EquipmentIdNO { get; set; }
        public string EquipmentContan { get; set; }
        public Nullable<int> FatalInjuryCrewNr { get; set; }
        public Nullable<int> FatalInjuryPassengerNr { get; set; }
        public Nullable<int> FatalInjuryOtherNr { get; set; }
        public Nullable<int> SeriousInjuryCrewNr { get; set; }
        public Nullable<int> SeriousInjuryPassengerNr { get; set; }
        public Nullable<int> SeriousInjuryOtherNr { get; set; }
        public Nullable<int> MinorInjuryCrewNr { get; set; }
        public Nullable<int> MinorInjuryPassengerNr { get; set; }
        public Nullable<int> MinorInjuryOtherNr { get; set; }
        public Nullable<int> NoneInjuryCrewNr { get; set; }
        public Nullable<int> NoneInjuryPassengerNr { get; set; }
        public Nullable<int> NoneInjuryOtherNr { get; set; }
        public Nullable<int> DamageId { get; set; }
        public string DamageDetail { get; set; }
        public string PriorEventWX { get; set; }
        public string EventTimeWX { get; set; }
        public string ForcastWX { get; set; }
        public Nullable<bool> IsExplosivesGoods { get; set; }
        public Nullable<bool> IsRadioActiveGoods { get; set; }
        public string OtherDangerousGood { get; set; }
        public string EventDescription { get; set; }
    }
}
