//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qa_hazard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public qa_hazard()
        {
            this.qa_hazard_scope = new HashSet<qa_hazard_scope>();
            this.qa_hazard_attachment = new HashSet<qa_hazard_attachment>();
            this.qa_hazard_involved_part = new HashSet<qa_hazard_involved_part>();
            this.qa_hazard_involved_person = new HashSet<qa_hazard_involved_person>();
            this.qa_hazard_relevant = new HashSet<qa_hazard_relevant>();
            this.qa_hazard_relevant1 = new HashSet<qa_hazard_relevant>();
            this.qa_hazard_source = new HashSet<qa_hazard_source>();
            this.qa_hazard_category = new HashSet<qa_hazard_category>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string priority { get; set; }
        public string scope { get; set; }
        public Nullable<int> scope_id { get; set; }
        public string location { get; set; }
        public string gps_coordinate { get; set; }
        public Nullable<System.DateTime> date_occurred { get; set; }
        public string tracking_no { get; set; }
        public Nullable<int> department_id { get; set; }
        public string remark { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lang { get; set; }
        public Nullable<int> airport_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_hazard_scope> qa_hazard_scope { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_hazard_attachment> qa_hazard_attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_hazard_involved_part> qa_hazard_involved_part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_hazard_involved_person> qa_hazard_involved_person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_hazard_relevant> qa_hazard_relevant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_hazard_relevant> qa_hazard_relevant1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_hazard_source> qa_hazard_source { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<qa_hazard_category> qa_hazard_category { get; set; }
    }
}
