//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cms2_audit_plan
    {
        public int id { get; set; }
        public int program_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int type_id { get; set; }
        public string objective { get; set; }
        public Nullable<System.DateTime> planned_from { get; set; }
        public Nullable<System.DateTime> planned_to { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string planned_period_type { get; set; }
        public Nullable<int> planned_period_value { get; set; }
        public Nullable<int> planned_year { get; set; }
        public string priority { get; set; }
        public string audit_method { get; set; }
        public string execution_mode { get; set; }
        public string selection_basis { get; set; }
        public Nullable<int> planned_count { get; set; }
        public Nullable<int> department_id { get; set; }
        public string department_title { get; set; }
        public bool is_active { get; set; }
        public string notes { get; set; }
    }
}
