//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cms2_risk_log
    {
        public int id { get; set; }
        public int hazard_id { get; set; }
        public Nullable<int> risk_matrix_id { get; set; }
        public string assessment_type { get; set; }
        public System.DateTime assessment_date { get; set; }
        public string assessed_by { get; set; }
        public string assessed_role { get; set; }
        public Nullable<int> initial_severity_id { get; set; }
        public string initial_severity_code { get; set; }
        public string initial_severity_title { get; set; }
        public Nullable<int> initial_likelihood_id { get; set; }
        public string initial_likelihood_code { get; set; }
        public string initial_likelihood_title { get; set; }
        public Nullable<int> initial_risk_level_id { get; set; }
        public Nullable<int> residual_severity_id { get; set; }
        public string residual_severity_code { get; set; }
        public string residual_severity_title { get; set; }
        public Nullable<int> residual_likelihood_id { get; set; }
        public string residual_likelihood_code { get; set; }
        public string residual_likelihood_title { get; set; }
        public Nullable<int> residual_risk_level_id { get; set; }
    }
}
