//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_qa_all_entity
    {
        public int id { get; set; }
        public int type { get; set; }
        public string table_name { get; set; }
        public Nullable<int> entity_id { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> event_date { get; set; }
        public Nullable<int> flight_id { get; set; }
        public Nullable<int> phase_of_flight_Id { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public Nullable<int> status_by { get; set; }
        public Nullable<int> reporter_list_Id { get; set; }
        public Nullable<System.DateTime> sign_date { get; set; }
        public Nullable<int> reporter_id { get; set; }
        public Nullable<int> station_id { get; set; }
        public string status_title { get; set; }
        public string type_title { get; set; }
    }
}
