//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEFBVoyageReason
    {
        public Nullable<int> ReasonId { get; set; }
        public Nullable<int> VoyageReportId { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
    }
}
